app/distributor/forms.py
# -*- coding: utf-8 -*-
# -*- Mode: Python -*-
# vim:si:ai:et:sw=4:sts=4:ts=4

from flask_wtf import Form
from wtforms import SubmitField, SelectField, SelectMultipleField
from wtforms import widgets
from ..models import Dcp

class MultiCheckboxField(SelectMultipleField):
    widget = widgets.Input()
    option_widget = widgets.CheckboxInput()

class ConfirmationForm(Form):
    submit = SubmitField(u'Valider la distribution')
    cancel = SubmitField(u'Annuler')


choices = [
    (Dcp.TRAILER, u'Bande Annonce (TLR)'),
    (Dcp.FEATURE, u'Long métrage (FTR)'),
]

class SelectDistributionTypeForm(Form):
    dist_type = MultiCheckboxField('A distribuer ', choices=choices)
    submit = SubmitField('Continuer')
    cancel = SubmitField('Annuler')

app/distributor/__init__.py
from flask import Blueprint

distributor = Blueprint('distributor', __name__)

distributor_movies = Blueprint('distributor_movies', __name__, template_folder="distributor/movies/")
distributor_movie_requests = Blueprint('distributor_movie_requests', __name__, template_folder="distributor/movie_requests/")

from . import views
from . import forms
from . import distribution
from . import movies
from . import movie_requests

app/distributor/views.py
# -*- coding: utf-8 -*-
# -*- Mode: Python -*-

import os.path
import sys

from flask import render_template, session, redirect, url_for, request
from flask import current_app, flash, jsonify
from flask_login import login_required, current_user
from flask_wtf import Form
from sqlalchemy import func

from . import distributor
from .. import db
from ..models import User, Movie, Exhibitor, DistributionStatus, Dcp, Short
from ..models import Distribution, MovieRequest, Distributor
from ..email import send_email, build_to
from ..decorators import distributor_required
from .forms import ConfirmationForm, SelectDistributionTypeForm
from .distribution import do_distribution

from app.datatables import ColumnDT, DataTables
from app.exceptions import TucoException
from app.common   import redirect_url

from string import upper

@distributor.route('/distributor/')
@distributor.route('/distributor/home')
@login_required
@distributor_required
def home():
    _d = current_user.distributor
    if _d.is_agencecm:
        shorts = Short.query.filter_by(distributor = _d).all()
        return render_template('distributor/agencecm_view.html',
                           title='Tuco',
                           distributor = _d,
                           shorts = shorts
                    )
    else:
        movies =_d.movies.filter_by(valid=True).order_by(Movie.releasedate.desc()).limit(4)
        return render_template('distributor/distributor_view.html',
                           title='Tuco',
                           distributor = _d,
                           movies = movies
                           )

@distributor.route('/distributor/distribute_movie/<int:movieid>', methods=['GET','POST'])
@login_required
@distributor_required
def distribute_movie(movieid):
    app = current_app._get_current_object()
    movie = Movie.query.get_or_404(movieid)
    exhibitors = Exhibitor.all_valid_exhibitors()

    form = Form()
    if form.validate_on_submit():
        if request.form.get('cancel'):
            flash(u'Distribution annulée')
            return redirect(url_for('distributor_movies.details', id = movie.movieid ))

        elif request.form.get('submit'):
            session['exhibitors'] = request.form.getlist('exhibitors')
            session['selected_dcps'] =  request.form.getlist('dcps')
            return redirect(url_for('distributor.distribute_movie_confirmation',
                                movieid = movieid))

        else:
            _msg=u'unkown POST directive'
            app.logger.error(_msg)
            flash(_msg)


    return render_template('distributor/distribute_movie.html',
        movie = movie,
        form = form)



@distributor.route('/distributor/distribute_movie_confimation/<int:movieid>', methods=['GET','POST'])
@distributor.route('/distributor/distribute_movie_confimation/<int:movieid>/<int:exhibitorid>', methods=['GET','POST'])
@login_required
@distributor_required
def distribute_movie_confirmation(movieid, exhibitorid=None):
    movie = Movie.query.get_or_404(movieid)
    app = current_app._get_current_object()
    if exhibitorid is None:
        exhibitors   = [Exhibitor.query.get(_id) for _id in session['exhibitors']]
        selected_dcps = [Dcp.query.get(_id) for _id in session['selected_dcps']]
    else:
        exhibitors = [Exhibitor.query.get_or_404(exhibitorid)]
        selected_dcps = movie.get_all_dcps()
    if not exhibitors:
        _msg = u'Pas d\'exploitant sélectionné: Distribution impossible'
        flash(_msg)
        current_app.logger.warning(_msg)
        return redirect(url_for('.distribute_movie', movieid = movieid))

    form = ConfirmationForm()
    if form.validate_on_submit():
        if form.cancel.data:
            flash(u'Distribution annulée')
            return redirect(url_for('distributor_movies.details', id = movieid))
        elif form.submit.data:
            exhibitors_ok = []
            for exhibitor in exhibitors:
                try:
                     _added_dcps = do_distribution(movie, selected_dcps, exhibitor)
                except TucoException as err:
                    flash(err.message)
                    continue
                if _added_dcps is not None:
                    exhibitors_ok.append(exhibitor)
                else:
                    _msg = u"L'exploitant {} est déjà autorisé à recevoir :{}".\
                            format(exhibitor, ' '.join([ _dcp.name for _dcp in selected_dcps] ))
                    flash(_msg)
            # send recap email to ditributor
            if exhibitors_ok:
                try:
                    send_email(
                        build_to(current_user.distributor),
                        u'Récapitulatif distribution de {}'.format(movie.title),
                        'distributor/email/recap_distribution',
                        cc = [app.config['TUCO_ADMIN']],
                        movie = movie,
                        selected_dcps = selected_dcps,
                        exhibitors = exhibitors_ok)
                except:
                    _msg = u'Something goes wrong in expedition'
                    flash(_msg)
                    _msg= u'Unexpected error:', sys.exc_info()[0]
                    current_app.logger.error(_msg)
            return redirect(url_for('distributor_movies.details', id = movieid))
        else:
            current_app.logger.error(u'Something goes wrong')
            return redirect(url_for('distributor_movies.details', id = movieid))
    return render_template('distributor/distribute_movie_confirmation.html',
                            movie = movie,
                            dcps = selected_dcps,
                            exhibitors = exhibitors,
                            form = form)

@distributor.route('/distributor/exhibitors')
@login_required
@distributor_required
def exhibitors():
    exhibitors = Exhibitor.query.order_by(Exhibitor.name)
    return render_template('distributor/exhibitors.html',
                            exhibitors = exhibitors)

@distributor.route('/distributor/exhibitor/<int:exhibitorid>', methods=['GET','POST'])
@login_required
@distributor_required
def show_exhibitor(exhibitorid):
    _d = current_user.distributor
    exhibitor = Exhibitor.query.get_or_404(exhibitorid)

    return render_template('distributor/exhibitor.html',
                           exhibitor = exhibitor,
                           distributor= _d)

@distributor.route('/distributor/list_demands', methods=('GET', 'POST'))
@login_required
@distributor_required
def list_demands():
    distributor = current_user.distributor
    demands = MovieRequest.query.filter_by(distributor = distributor).all()
    return render_template('distributor/list_demands.html',
                            demands = demands)

@distributor.route('/distributor/distributiondata')
@login_required
@distributor_required
def distributiondata():
    """Return server side data."""
    # defining columns
    columns = []
    columns.append(ColumnDT('dcp.movie.title','movie'))
    columns.append(ColumnDT('dcp.name','dcp' ))
    columns.append(ColumnDT('dcp.movie.distributor.name','distributor'))
    columns.append(ColumnDT('exhibitor.name', 'exhibitor'))
    columns.append(ColumnDT('autorisation_date', 'autorisation_date', search_like = False, search_datetime_range = True))
    columns.append(ColumnDT('started_transfer_date','started_transfer_date',  search_like = False, search_datetime_range = True))
    columns.append(ColumnDT('finished_transfer_date', 'finished_transfer_date', search_like = False, search_datetime_range = True))
    columns.append(ColumnDT('dcp.contentkind', 'contentkind', searchable  =False))
    columns.append(ColumnDT('dcp.movie.movieid', 'movieid',  searchable  =False))
    columns.append(ColumnDT('dcp.movie.distributor.distributorid','distributorid', searchable  =False))
    columns.append(ColumnDT('exhibitor.exhibitorid', 'exhibitorid', searchable  =False))
    columns.append(ColumnDT('dcp.dcpid', 'dcpid', searchable  =False))
    columns.append(ColumnDT('dcp.valid', 'valid', searchable  =False))
    columns.append(ColumnDT('exhibitor.city', 'city', searchable  =False, filter= upper) )

    try:
        _e = int( request.values['exhibitor'])
    except ValueError:
        _e = None

    try:
        _d = int( request.values['distributor'])
    except ValueError:
        _d = None

    try:
        _m = int( request.values['movie'])
    except ValueError:
        _m = None

    query = db.session.query(Distribution).join(Dcp).join(Exhibitor).join(Movie).join(Distributor)
    if _e is not None:
        query = query.filter(Exhibitor.exhibitorid == _e)
    if _d is not None:
        query = query.filter(Distributor.distributorid == _d)
    if _m is not None:
        query = query.filter(Movie.movieid == _m)
    from sqlalchemy import or_, and_
    query = query.filter(or_(
        and_(Dcp.contentkind == Dcp.FEATURE, Distribution.isauthorised ==True),
        and_( Dcp.contentkind == Dcp.TRAILER,
            or_( Distribution.autorisation_date != None,  Distribution.started_transfer_date !=None)
            )
        ))

    # instantiating a DataTable for the query and table needed
    rowTable = DataTables(request.args, Distribution, query, columns)
    # returns what is needed by DataTable
    return jsonify(rowTable.output_result())


from flask_restful import fields, marshal
from flask.json import dumps

class StatusField(fields.Raw):
    DISTRIBUTION_STATUS = {
            DistributionStatus.DL_NOT_AUTHORIZED : u'Distribution not allowed',
            DistributionStatus.DL_AUTHORIZED : u'Distribution allowed',
            DistributionStatus.DL_STARTED : u'Distribution started',
            DistributionStatus.DL_FINISHED : u'Distribution finished',
            DistributionStatus.DL_ERROR : u'Distribution error',
            }


    def format(self, value):
        return self.DISTRIBUTION_STATUS[value]

app/templates/distributor/movie_requests/_tables.html
{% from "distributor/movie_requests/_modals.html" import contact_modal_html %}
{% from "distributor/movie_requests/_modals.html" import distribute_movie_modal_html %}
{% from "distributor/movie_requests/_modals.html" import deny_modal_html %}

{% macro table_html( ) %}
<div class="row">
    <table id="DefaultTable" class="table table-striped table-bordered table-condensed table-summary">
        <thead>
            <tr>
                <th> Date demande</th>
                <th> Exploitant</th>
                <th> Date programmé </th>
                <th> Film </th>
                <th> Statut </th>
                <th> Date autorisation / refus </th>
                <th> Actions  </th>
            </tr>
        </thead>
    </table>
</div>


{{ contact_modal_html() }}
{{ distribute_movie_modal_html() }}
{{ deny_modal_html() }}
{% endmacro %}


{% macro table_js(query_type='all' ) %}
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
    update_locales();
    var table = $('#DefaultTable').DataTable({
        "order" : [[0, 'desc']],
        "ajax": {
            "url": "{{ url_for('.movie_request_data', query_type=query_type) }}",
        },
        "columns": [
       {
            "data": "demand_date",
            "render": function ( data, type, row ) {
                var $todisplay = $("<div>");
                var cel_text = $('<span>', {
                    'text': render_date(data,type) +
                        ' (' + moment(data).fromNow() + ')',
                }).appendTo($todisplay);

                if (data != row.first_demand_date) {
                    $("<br>").appendTo($todisplay);
                    $("<span>",{
                        'text': '1ere demande le ' +
                        render_date(row.demand_date,type) +
                        ' (' + moment(row.demand_date).fromNow() + ')',
                    }).appendTo($todisplay);
                    }
                return $todisplay.html();
            },
        },
        {
            "data": "exhibitor",
            "render": function ( data, type, row ) {
                var $todisplay = $("<div>");
                var href=   "{{ url_for('distributor.show_exhibitor', exhibitorid = -1) }}"
                href = href.replace("/-1", "/"+row.exhibitorid);

                var $link = $('<a>',{
                    'href': href,
                }).appendTo($todisplay);

                $('<span>', {
                    'text': data
                }).appendTo($link);

                return $todisplay.html();
            },
        },
       {
            "data": "programed_date",
            "render": function ( data, type, row ) {
                var $todisplay = $("<div>");
                var cel_text = $('<span>', {
                    'text': render_date(data,type)});
                cel_text.appendTo($todisplay);
                return $todisplay.html();
            },
        },
        {
            "data": "movie",
            "render": function ( data, type, row ) {
                var $todisplay = $("<div>");
                var href=   "{{ url_for('distributor_movies.details', id = -1) }}"
                href = href.replace("/-1", "/"+row.movieid);

                var $link = $('<a>',{
                    'href': href,
                }).appendTo($todisplay);

                $('<span>', {
                    'text': data
                }).appendTo($link);

                return $todisplay.html();
           }
        },
       {
            "data": "status",
            "class": "status",
            "render": function ( data, type, row ) {
                var $todisplay = $("<div>");
                $("<div>",{
                    'class': 'status ' + statusStr[row.statusId].class,
                    'text': statusStr[row.statusId].str,
                }).appendTo($todisplay);
                if ( row.status == 'DENIED' ) {
                    var $div = $("<div>");
                     $('<span>',{
                        'text':  'motif:'
                    }).appendTo($div);
                    $('<br>').appendTo($div);

                    $('<span>',{
                        'text': DenyCauseStr[row.deny_causeId].str,
                    }).appendTo($div);
                    if (row.deny_other_cause) {
                        $('<br>').appendTo($div);
                        $('<span>',{
                            'text': row.deny_other_cause,
                        }).appendTo($div);
                    }

                    $div.appendTo($todisplay);
                }

                return $todisplay.html();

            },
        },
        { "data": "null",

            "render": function ( data, type, row ) {
                var $todisplay = $("<div>");
                var cel_text = $('<span>');
                switch( row.status) {
                    case 'ALLOWED':
                        cel_text.text(render_date(row.allow_date, type));
                        break;
                    case 'DENIED':
                        cel_text.text(render_date(row.deny_date, type));
                        break;
                    default:
                        break;
                }
                cel_text.appendTo($todisplay);
                return $todisplay.html();
            }
        },
        {
            "data": null ,
            "render": function ( data, type, row ) {
                var $todisplay = $("<div>");
                return DisplayButtongroup($todisplay, row.status, 'distributor').html();

            },
        },
        ],
    });

    $('#DefaultTable tbody ').on( 'click', 'button.action-allow',  function(event){

        var row = table.row( $(this).parents('tr') )
        var data = row.data();

        var csrftoken = $('meta[name=csrf-token]').attr('content');
        var span_msg = $(this).parents('tr').find('span.status_msg');

        console.log('Action autoriser ');

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        });


        var posting = $.ajax({
            url: 'do_get_movie_data',
            type: 'POST',
            data: JSON.stringify({'id': data.id}),
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            async: true,
        });

        posting.done( function(post_data) {

            $('#DistributeModal').modal()
            $('#DistributeModal #movierequestid').attr('value', data.id);
            $('#DistributeModal #Ditributemodal_movie').text(data.movie);
            var ul = $('#DistributeModal #Ditributemodal_dcps')
            ul.empty()
            for ( var i= 0 ; i <post_data.dcps.length; i++) {
                           var dcp = post_data.dcps[i];
                           console.log(dcp.name);
                           var li = $('<li>', {
                               class: 'list-group-item',
                           }).appendTo(ul);

                           $('<span>',{
                               'text': dcp.name,
                           }).appendTo(li);
                           render_contentkind_label(dcp.contentkind, false).prependTo(li)
                }

            $('#DistributeModal #Ditributemodal_exhibitor').text(data.exhibitor);
            // table.ajax.reload();
        });

        posting.fail( function( jqXHR, textStatus ) {
            alert( "Request failed: " + textStatus );
        });

    });

    $('#DefaultTable tbody ').on( 'click', 'button.action-deny',  function(event){


        var data = table.row( $(this).parents('tr') ).data();

        var csrftoken = $('meta[name=csrf-token]').attr('content');
        var span_msg = $(this).parents('tr').find('span.status_msg');

        console.log('Action deny');

        $('#DenyModal #movierequestid').attr('value', data.id);
        $('#DenyModal #exhibitorid').attr('value', data.exhibitorid);
        $('#DenyModal #movieid').attr('value', data.movieid);
        $('#DenyModal #distributorid').attr('value', data.distributorid);
        $('#DenyModal input.from').attr('value', data.distributor);
        $('#DenyModal input.to').attr('value', data.exhibitor);
        $('#DenyModal input.movie').attr('value', data.movie);
        $('#DenyModal').modal()
        //TODO: Modal with mail dialog
    });

    $('#DefaultTable tbody ').on( 'click', 'button.action-contact',  function(event){


        var data = table.row( $(this).parents('tr') ).data();


        console.log('Action contact');

        $('#ContactModal #movierequestid').attr('value', data.id);
        $('#ContactModal #exhibitorid').attr('value', data.exhibitorid);
        $('#ContactModal #movieid').attr('value', data.movieid);
        $('#ContactModal #distributorid').attr('value', data.distributorid);
        $('#ContactModal input.from').attr('value', data.distributor);
        $('#ContactModal input.to').attr('value', data.exhibitor);
        $('#ContactModal input.movie').attr('value', data.movie);
        $('#ContactModal').modal()
        //TODO: Modal with mail dialog
    });

    $('#DefaultTable tbody ').on( 'click', 'button.action-consult',  function(event){

        var data = table.row( $(this).parents('tr') ).data();
        location.href = 'details/'+data.id;

    });


    $("#formDeny").submit(function(e) {
        e.preventDefault()
        console.log("submit button clicked!");
        console.log( $(this).serialize() );

        var csrftoken = $('meta[name=csrf-token]').attr('content');

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        });


        var posting = $.ajax({
            url: 'do_deny',
            type: 'POST',
            data: JSON.stringify( $(this).serializeArray() ),
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            async: true,
        });
        posting.done( function(post_data) {
            table.ajax.reload();
        });
        posting.fail( function( jqXHR, textStatus ) {
            alert( "Request failed: " + textStatus );
        });


        $('#DenyModal').modal('hide')

    });

    $("#formDistribute").submit(function(e) {
        e.preventDefault()
        console.log("submit button clicked!");
        console.log( $(this).serialize() );

        var csrftoken = $('meta[name=csrf-token]').attr('content');

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        });


        var posting = $.ajax({
            url: 'do_allow',
            type: 'POST',
            data: JSON.stringify( $(this).serializeArray() ),
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            async: true,
        });
        posting.done( function(post_data) {
            table.ajax.reload();
        });
        posting.fail( function( jqXHR, textStatus ) {
            alert( "Request failed: " + textStatus );
        });


        $('#DistributeModal').modal('hide')

    });


    $("#formContact").submit(function(e) {
        e.preventDefault()
        console.log("submit button clicked!");
        console.log( $(this).serialize() );

        var csrftoken = $('meta[name=csrf-token]').attr('content');

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        });


        var posting = $.ajax({
            url: 'do_contact',
            type: 'POST',
            data: JSON.stringify( $(this).serializeArray() ),
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            async: true,
        });

        posting.done( function(post_data) {
            table.ajax.reload();
        });
        posting.fail( function( jqXHR, textStatus ) {
            alert( "Request failed: " + textStatus );
        });

        $('#ContactModal').modal('hide')

    });

});

</script>


{% endmacro %}

app/templates/distributor/movie_requests/all.html
{% extends "base.html" %}
{% from "distributor/movie_requests/_tables.html" import table_html, table_js %}

{% block head %}
{{ super() }}
<meta name="csrf-token" content="{{ csrf_token() }}">

{% endblock %}

{% block page_content %}
<div class="page-header">
<ul class="nav nav-tabs">
    <li role="presentation" ><a href="{{ url_for('.home') }}" > En attente </a> </li>
    <li role="presentation"> <a href="{{ url_for('.new') }}" > Récentes </a> </li>
    <li role="presentation" class="active"><a href="{{ url_for('.all') }}" > Toutes </a></li>
</ul>
<h2> Historique des demandes  </h2>
</div>

{{ table_html() }}

{% endblock %}


{% block scripts %}
{{ super() }}

<script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/datetime-moment.js') }}"></script>

{{ table_js( query_type='all') }}

{% endblock %}

app/templates/distributor/movie_requests/home.html
{% extends "base.html" %}
{% from "distributor/movie_requests/_tables.html" import table_html, table_js %}

{% block head %}
{{ super() }}
<meta name="csrf-token" content="{{ csrf_token() }}">

{% endblock %}

{% block page_content %}
<div class="page-header">
<ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="{{ url_for('.home') }}" > En attente </a> </li>
        <li role="presentation" ><a href="{{ url_for('.new') }}" > Récentes </a> </li>
        <li role="presentation" ><a href="{{ url_for('.all') }}" > Toutes </a> </li>
</ul>
<h2> Demandes en attente </h2>
<p> Retrouvez ici les demandes de salles en attente. </p>
</div>

{{ table_html() }}

{% endblock %}

{% block scripts %}
{{ super() }}

<script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/datetime-moment.js') }}"></script>

{{ table_js( query_type='pending') }}

{% endblock %}

app/templates/distributor/movie_requests/new.html
{% extends "base.html" %}
{% from "distributor/movie_requests/_tables.html" import table_html, table_js %}

{% block head %}
{{ super() }}
<meta name="csrf-token" content="{{ csrf_token() }}">

{% endblock %}

{% block page_content %}
<div class="page-header">
<ul class="nav nav-tabs">
        <li role="presentation" ><a href="{{ url_for('.home') }}" > En attente </a> </li>
        <li role="presentation" class="active"><a href="{{ url_for('.new') }}" > Récentes </a> </li>
        <li role="presentation" ><a href="{{ url_for('.all') }}" > Toutes </a> </li>
</ul>
<h2> Les demandes récentes  </h2>
<p>  Retrouvez ici toutes vos demandes et actions récentes  </p>
</div>

{{ table_html() }}

{% endblock %}

{% block scripts %}
{{ super() }}

<script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/datetime-moment.js') }}"></script>

{{ table_js( query_type='new') }}

{% endblock %}