app/distributor/forms.py
# -*- coding: utf-8 -*-
# -*- Mode: Python -*-
# vim:si:ai:et:sw=4:sts=4:ts=4

from flask_wtf import Form
from wtforms import SubmitField, SelectField, SelectMultipleField
from wtforms import widgets
from ..models import Dcp

class MultiCheckboxField(SelectMultipleField):
    widget = widgets.Input()
    option_widget = widgets.CheckboxInput()

class ConfirmationForm(Form):
    submit = SubmitField(u'Valider la distribution')
    cancel = SubmitField(u'Annuler')


choices = [
    (Dcp.TRAILER, u'Bande Annonce (TLR)'),
    (Dcp.FEATURE, u'Long métrage (FTR)'),
]

class SelectDistributionTypeForm(Form):
    dist_type = MultiCheckboxField('A distribuer ', choices=choices)
    submit = SubmitField('Continuer')
    cancel = SubmitField('Annuler')

app/distributor/__init__.py
from flask import Blueprint

distributor = Blueprint('distributor', __name__)

distributor_movies = Blueprint('distributor_movies', __name__, template_folder="distributor/movies/")
distributor_movie_requests = Blueprint('distributor_movie_requests', __name__, template_folder="distributor/movie_requests/")

from . import views
from . import forms
from . import distribution
from . import movies
from . import movie_requests

app/distributor/views.py
# -*- coding: utf-8 -*-
# -*- Mode: Python -*-

import os.path
import sys

from flask import render_template, session, redirect, url_for, request
from flask import current_app, flash, jsonify
from flask_login import login_required, current_user
from flask_wtf import Form
from sqlalchemy import func

from . import distributor
from .. import db
from ..models import User, Movie, Exhibitor, DistributionStatus, Dcp, Short
from ..models import Distribution, MovieRequest, Distributor
from ..email import send_email, build_to
from ..decorators import distributor_required
from .forms import ConfirmationForm, SelectDistributionTypeForm
from .distribution import do_distribution

from app.datatables import ColumnDT, DataTables
from app.exceptions import TucoException
from app.common   import redirect_url

from string import upper

@distributor.route('/distributor/')
@distributor.route('/distributor/home')
@login_required
@distributor_required
def home():
    _d = current_user.distributor
    if _d.is_agencecm:
        shorts = Short.query.filter_by(distributor = _d).all()
        return render_template('distributor/agencecm_view.html',
                           title='Tuco',
                           distributor = _d,
                           shorts = shorts
                    )
    else:
        movies =_d.movies.filter_by(valid=True).order_by(Movie.releasedate.desc()).limit(4)
        return render_template('distributor/distributor_view.html',
                           title='Tuco',
                           distributor = _d,
                           movies = movies
                           )

@distributor.route('/distributor/distribute_movie/<int:movieid>', methods=['GET','POST'])
@login_required
@distributor_required
def distribute_movie(movieid):
    app = current_app._get_current_object()
    movie = Movie.query.get_or_404(movieid)
    exhibitors = Exhibitor.all_valid_exhibitors()

    form = Form()
    if form.validate_on_submit():
        if request.form.get('cancel'):
            flash(u'Distribution annulée')
            return redirect(url_for('distributor_movies.details', id = movie.movieid ))

        elif request.form.get('submit'):
            session['exhibitors'] = request.form.getlist('exhibitors')
            session['selected_dcps'] =  request.form.getlist('dcps')
            return redirect(url_for('distributor.distribute_movie_confirmation',
                                movieid = movieid))

        else:
            _msg=u'unkown POST directive'
            app.logger.error(_msg)
            flash(_msg)


    return render_template('distributor/distribute_movie.html',
        movie = movie,
        form = form)



@distributor.route('/distributor/distribute_movie_confimation/<int:movieid>', methods=['GET','POST'])
@distributor.route('/distributor/distribute_movie_confimation/<int:movieid>/<int:exhibitorid>', methods=['GET','POST'])
@login_required
@distributor_required
def distribute_movie_confirmation(movieid, exhibitorid=None):
    movie = Movie.query.get_or_404(movieid)
    app = current_app._get_current_object()
    if exhibitorid is None:
        exhibitors   = [Exhibitor.query.get(_id) for _id in session['exhibitors']]
        selected_dcps = [Dcp.query.get(_id) for _id in session['selected_dcps']]
    else:
        exhibitors = [Exhibitor.query.get_or_404(exhibitorid)]
        selected_dcps = movie.get_all_dcps()
    if not exhibitors:
        _msg = u'Pas d\'exploitant sélectionné: Distribution impossible'
        flash(_msg)
        current_app.logger.warning(_msg)
        return redirect(url_for('.distribute_movie', movieid = movieid))

    form = ConfirmationForm()
    if form.validate_on_submit():
        if form.cancel.data:
            flash(u'Distribution annulée')
            return redirect(url_for('distributor_movies.details', id = movieid))
        elif form.submit.data:
            exhibitors_ok = []
            for exhibitor in exhibitors:
                try:
                     _added_dcps = do_distribution(movie, selected_dcps, exhibitor)
                except TucoException as err:
                    flash(err.message)
                    continue
                if _added_dcps is not None:
                    exhibitors_ok.append(exhibitor)
                else:
                    _msg = u"L'exploitant {} est déjà autorisé à recevoir :{}".\
                            format(exhibitor, ' '.join([ _dcp.name for _dcp in selected_dcps] ))
                    flash(_msg)
            # send recap email to ditributor
            if exhibitors_ok:
                try:
                    send_email(
                        build_to(current_user.distributor),
                        u'Récapitulatif distribution de {}'.format(movie.title),
                        'distributor/email/recap_distribution',
                        cc = [app.config['TUCO_ADMIN']],
                        movie = movie,
                        selected_dcps = selected_dcps,
                        exhibitors = exhibitors_ok)
                except:
                    _msg = u'Something goes wrong in expedition'
                    flash(_msg)
                    _msg= u'Unexpected error:', sys.exc_info()[0]
                    current_app.logger.error(_msg)
            return redirect(url_for('distributor_movies.details', id = movieid))
        else:
            current_app.logger.error(u'Something goes wrong')
            return redirect(url_for('distributor_movies.details', id = movieid))
    return render_template('distributor/distribute_movie_confirmation.html',
                            movie = movie,
                            dcps = selected_dcps,
                            exhibitors = exhibitors,
                            form = form)

@distributor.route('/distributor/exhibitors')
@login_required
@distributor_required
def exhibitors():
    exhibitors = Exhibitor.query.order_by(Exhibitor.name)
    return render_template('distributor/exhibitors.html',
                            exhibitors = exhibitors)

@distributor.route('/distributor/exhibitor/<int:exhibitorid>', methods=['GET','POST'])
@login_required
@distributor_required
def show_exhibitor(exhibitorid):
    _d = current_user.distributor
    exhibitor = Exhibitor.query.get_or_404(exhibitorid)

    return render_template('distributor/exhibitor.html',
                           exhibitor = exhibitor,
                           distributor= _d)

@distributor.route('/distributor/list_demands', methods=('GET', 'POST'))
@login_required
@distributor_required
def list_demands():
    distributor = current_user.distributor
    demands = MovieRequest.query.filter_by(distributor = distributor).all()
    return render_template('distributor/list_demands.html',
                            demands = demands)

@distributor.route('/distributor/distributiondata')
@login_required
@distributor_required
def distributiondata():
    """Return server side data."""
    # defining columns
    columns = []
    columns.append(ColumnDT('dcp.movie.title','movie'))
    columns.append(ColumnDT('dcp.name','dcp' ))
    columns.append(ColumnDT('dcp.movie.distributor.name','distributor'))
    columns.append(ColumnDT('exhibitor.name', 'exhibitor'))
    columns.append(ColumnDT('autorisation_date', 'autorisation_date', search_like = False, search_datetime_range = True))
    columns.append(ColumnDT('started_transfer_date','started_transfer_date',  search_like = False, search_datetime_range = True))
    columns.append(ColumnDT('finished_transfer_date', 'finished_transfer_date', search_like = False, search_datetime_range = True))
    columns.append(ColumnDT('dcp.contentkind', 'contentkind', searchable  =False))
    columns.append(ColumnDT('dcp.movie.movieid', 'movieid',  searchable  =False))
    columns.append(ColumnDT('dcp.movie.distributor.distributorid','distributorid', searchable  =False))
    columns.append(ColumnDT('exhibitor.exhibitorid', 'exhibitorid', searchable  =False))
    columns.append(ColumnDT('dcp.dcpid', 'dcpid', searchable  =False))
    columns.append(ColumnDT('dcp.valid', 'valid', searchable  =False))
    columns.append(ColumnDT('exhibitor.city', 'city', searchable  =False, filter= upper) )

    try:
        _e = int( request.values['exhibitor'])
    except ValueError:
        _e = None

    try:
        _d = int( request.values['distributor'])
    except ValueError:
        _d = None

    try:
        _m = int( request.values['movie'])
    except ValueError:
        _m = None

    query = db.session.query(Distribution).join(Dcp).join(Exhibitor).join(Movie).join(Distributor)
    if _e is not None:
        query = query.filter(Exhibitor.exhibitorid == _e)
    if _d is not None:
        query = query.filter(Distributor.distributorid == _d)
    if _m is not None:
        query = query.filter(Movie.movieid == _m)
    from sqlalchemy import or_, and_
    query = query.filter(or_(
        and_(Dcp.contentkind == Dcp.FEATURE, Distribution.isauthorised ==True),
        and_( Dcp.contentkind == Dcp.TRAILER,
            or_( Distribution.autorisation_date != None,  Distribution.started_transfer_date !=None)
            )
        ))

    # instantiating a DataTable for the query and table needed
    rowTable = DataTables(request.args, Distribution, query, columns)
    # returns what is needed by DataTable
    return jsonify(rowTable.output_result())


from flask_restful import fields, marshal
from flask.json import dumps

class StatusField(fields.Raw):
    DISTRIBUTION_STATUS = {
            DistributionStatus.DL_NOT_AUTHORIZED : u'Distribution not allowed',
            DistributionStatus.DL_AUTHORIZED : u'Distribution allowed',
            DistributionStatus.DL_STARTED : u'Distribution started',
            DistributionStatus.DL_FINISHED : u'Distribution finished',
            DistributionStatus.DL_ERROR : u'Distribution error',
            }


    def format(self, value):
        return self.DISTRIBUTION_STATUS[value]

app/templates/distributor/movies/all.html
{% extends "base.html" %}

{% block page_content %}

<div class="container-fluid">
    <div class = "row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-header" >
                    <h3>  Mon catalogue </h3>
                </div>
                <div class="panel-body" >
                    <table id="DefaultTable" class="table table-striped table-bordered table-condensed table-summary" >
                        <thead>
                            <tr>
                                <th> Film  </th>
                                <th> Date de sortie </th>
                                <th> FTR disponible(s) </th>
                                <th> TLR disponibles(s) </th>
                                <th> Action </th>
                            </tr>
                        </thead>
                        {% for item in movies %}
                        <tr>
                            <td>  <a href = "{{ url_for('.details', id = item.movieid) }}" > {{ item.title }} </a></td>
                            <td>
                                {{ item.releasedate }}
                            </td>
                            <td>
                                {% if item.nb_valid_ftr > 0 %}
                                <span class="glyphicon glyphicon-ok" style="color:green" aria-hidden="true"></span>
                                {% else %}
                                <span class="glyphicon glyphicon-remove" style="color:red" aria-hidden="true"></span>
                                {% endif %}
                                {{ item.nb_valid_ftr}}
                            </td>
                            <td>
                                {% if item.nb_valid_tlr > 0 %}
                                <span class="glyphicon glyphicon-ok" style="color:green" aria-hidden="true"></span>
                                {% else %}
                                <span class="glyphicon glyphicon-remove" style="color:red" aria-hidden="true"></span>
                                {% endif %}
                                {{ item.nb_valid_tlr}}
                            </td>
                            <td> <a href="{{ url_for('distributor.distribute_movie', movieid= item.movieid) }}" class="btn btn-primary" role="button">Distribuer</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
{{ super() }}

<script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/datetime-moment.js') }}"></script>

<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
    update_locales();
    var table =$('#DefaultTable').DataTable({
        'columnDefs': [
        {
            'targets': 1,
            'visible': true,
            "render": function ( data, type, row ) {
                return render_date(data,type);
            }
        }
         ],
        "order" : [[1, 'desc']]
    });
} );
</script>

{% endblock %}

app/templates/distributor/movies/details.html
{% extends "baseV2.html" %}

{% from "distributor/_table_distribution.html" import table_distribution_head %}
{% from "distributor/_table_distribution.html" import table_distribution %}
{% from "distributor/_table_distribution.html" import table_distribution_scripts %}
{% from "_distribution_status.html" import contentkind_label %}
{% from "admin/movies/_macros.html" import movie_extra %}
{% from "_common_macros.html" import item_valid %}

{% block head %}
{{ super() }}
{{ table_distribution_head() }}
{% endblock %}


{% block page_content %}

<div class="container-fluid">
    <div class="page-header">
        <h1>{{movie.title}} <a href="{{ url_for('distributor.distribute_movie', movieid= movie.movieid) }}" class="btn btn-primary" role="button">Distribuer </a> </h1>

    </div>
</div>

<div class="container-fluid">
    <div class="row" >
        <div class="col-md-8" >
            <div class="panel panel-default">
                <table class="table table-striped table-bordered table-condensed" >
                    <tr>
                        <td> Titre </td>
                        <td>
                            {{ item_valid(movie.valid, movie.title) }}
                        </td>
                    </tr>
        {% if movie.distributor.original_title %}
        <tr>
            <td> Titre original: </td>
            <td> {{ movie.distributor.name }} </td>
        </tr>
        {% endif %}
        <tr>
            <td> Date de sortie: </td>
            <td> {{ movie.releasedate | datefr }} </td>
        </tr>
        {% if movie.catalogues %}
        <tr>
            <td> Catalogue </td>
            <td>
                {% for cata in movie.catalogues %}
                <span> {{ cata.name }} </span>
                {% endfor %}
            </td>
        </tr>

        {% endif %}

        {% if movie.tags %}
        <tr>
            <td> Tags </td>
            <td>
                {% for tag in movie.tags %}
                <span>  {{ tag.name }} </span>
                {% endfor %}
            </td>
        </tr>
        {% endif %}
        {{ movie_extra(movie.extra) }}

                </table>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12" >
            {% if movie.dcps %}
            <h3> DCPs associés: </h3>
            <table id="DcpTable" class="table table-striped table-bordered table-condensed" >
                <thead>
                    <tr>
                        <th> DCP </th>
                        <th> Taille </th>
                        <th> Date de mise à disposition </th>
                    </tr>
                </thead>

                {% for _dcp in movie.dcps %}
                <tr>
                    <td>
                        <span> {{ contentkind_label(_dcp.contentkind)}} </span>
                            {{ item_valid(_dcp.valid, _dcp.name) }}
                    </td>

                    <td>
                        {% if _dcp.size %}
                            {{ item_valid(_dcp.valid, _dcp.size | filesizeformat) }}
                        {% endif %}
                    </td>
                    <td>
                        {% if _dcp.torrent_creation %}
                            {{ item_valid(_dcp.valid, _dcp.torrent_creation | mydatetime) }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
            <p> Pas de DCP associé à ce film. </p>
            {% endif %}
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class = "row">
        <div class="col-lg-12" >
            <h3> Distribution</h3>
        </div>
    </div>
    {{ table_distribution() }}
</div>

{% endblock %}

{% block scripts %}
{{ super() }}

<script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/datetime-moment.js') }}"></script>
<script type="text/javascript" charset="utf-8">
    update_locales();
$(document).ready(function() {
    var dcptable =$('#DcpTable').DataTable({
        "searching": false,
        "paging": false,
        "info": false,
        "columnDefs": [ {
          "targets": '_all',
          "orderable": false,
        } ]
    });
} );
</script>


{{ table_distribution_scripts(distributor=distributor, movie=movie) }}

{% endblock %}