app/exhibitor/forms.py
# -*- coding: utf-8 -*-
# -*- Mode: Python -*-

from flask_wtf import FlaskForm
from wtforms import widgets
from wtforms import TextField, TextAreaField, SubmitField
from wtforms import RadioField
from wtforms import SelectField
from wtforms import StringField
from wtforms import DateField
from wtforms.fields.html5 import EmailField
from wtforms import validators, ValidationError
class ContactForm(FlaskForm):
    name = TextField(u"Name",  [validators.Required()])
    email = TextField(u"Email",  [validators.Required()])
    subject = TextField(u"Sujet",  [validators.Required()])
    message = TextAreaField(u"Message",  [validators.Required()])
    submit = SubmitField(u"Send")

class AskforMovieForm(FlaskForm):
    name = TextField(u"Exploitant",  [validators.Required()])
    to = TextField(u"Envoyer à",  [validators.Required()])
    movie = TextField(u"Film",  [validators.Required()])
    programed_date = DateField(u"Date programmation", format=u"%d/%m/%Y", validators=(validators.Optional(),))
    message = TextAreaField(u"Message")
    submit = SubmitField(u"Envoyer le message")

class ReadonlyTextField(TextField):
      def __call__(self, *args, **kwargs):
          kwargs.setdefault('readonly', True)
          return super(ReadonlyTextField, self).__call__(*args, **kwargs)

class UserPropertiesForm(FlaskForm):
    name =      ReadonlyTextField(u"Cinéma")
    cncid =     TextField(u"Numéro d'autorisation CNC",  [validators.DataRequired()])
    contact =   TextField(u"Contact",  [validators.DataRequired()])
    email1 =     EmailField(u"Email principal",  [validators.DataRequired(),
                    validators.Email()])
    email2 =     EmailField(u"Email 2" )
    email3 =     EmailField(u"Email 3" )
    phone = StringField(u'Téléphones(s) -- séparé par des virgules')
    address =   TextField(u"Adresse",  [validators.DataRequired()])
    zipcode   = StringField(u'Code postal')
    dept =      TextField(u"Département",  [validators.DataRequired()])
    city =      TextField(u"Ville",  [validators.DataRequired()])
    nbscreens = TextField(u"Nombre d'écrans",  [validators.DataRequired()])

    startauto = SelectField(u'Démarrage automatique des transferts ?',
            validators = [ validators.Required() ],
            choices = [('yes',
                u"Oui -- Démarrer automatiquement le tansfert de DCP \
                        dés qu'il est autorisé par le distributeur"),
                ('no',
                    u'Non -- Pas de  démarrage automatique des transferts')],
                default = 'no')
    submit =    SubmitField(u"Envoyer")
    cancel =    SubmitField(u'Annuler les modifications')

app/exhibitor/__init__.py
from flask import Blueprint

exhibitor = Blueprint('exhibitor', __name__)
exhibitor_movies = Blueprint('exhibitor_movies', __name__, template_folder="exhibitor/movies/")
exhibitor_movie_requests = Blueprint('exhibitor_movie_requests', __name__, template_folder="exhibitor/movie_requests/")
exhibitor_distributors = Blueprint('exhibitor_distributors', __name__, template_folder="exhibitor/distributors/")
exhibitor_tags = Blueprint('exhibitor_tags', __name__, template_folder="exhibitor/tags/")
exhibitor_shorts = Blueprint('exhibitor_shorts', __name__, template_folder="exhibitor/shorts/")


from . import views
from . import movies
from . import movie_requests
from . import distributors
from . import forms
from . import actions
from . import tags
from . import shorts

app/exhibitor/views.py
# -*- coding: utf-8 -*-
# -*- Mode: Python -*-

import os.path
import sys
from datetime import date, datetime, timedelta

from flask import render_template, session, redirect, url_for, request, current_app, flash
from flask import send_from_directory, safe_join, jsonify
from flask_login import login_required, current_user
from flask_restful import fields, marshal
from sqlalchemy import or_, and_, func
from . import exhibitor
from .forms import UserPropertiesForm
from .. import db
from ..models import User, Movie, Exhibitor, DistributionStatus, Dcp
from ..models import Distribution, MovieRequest, Short, Distributor
from ..TorrentsModel import Torrent, Client, TorrentRequest, MonitoringStatus
from ..email import send_email_wo_template, build_to
from ..decorators import exhibitor_required
from ..torrent.transmission import TorrentClient
from ..torrent.BitTorrentClient import TransmissionClient
from ..exceptions import TucoException
from ..common import path2url, redirect_url
from ..filters import mydatetime_filter
from app.torrent.tools import format_torrent_data
from app.email import send_email
import json


from app.datatables import ColumnDT, DataTables

@exhibitor.route('/exhibitor/')
@exhibitor.route('/exhibitor/home')
@login_required
@exhibitor_required
def home(page=1):
    app = current_app._get_current_object()
    exhibitor = current_user.exhibitor
    return render_template('exhibitor/exhibitor_view.html',
                           exhibitor = exhibitor
                           )

def cinema_status(exhibitor):
    res = MonitoringStatus.query.filter_by(ipt=exhibitor.iptinc).one()
    data = {
            u'exhibitor': exhibitor.name,
            u'iptinc'   : res.ipt,
            u'status'   : res.status,
            }
    return data

@exhibitor.route('/exhibitor/getcinemastatus')
@login_required
@exhibitor_required
def getcinemastatus():
    app = current_app._get_current_object()
    exhibitor = current_user.exhibitor
    data = cinema_status(exhibitor)
    return jsonify(exhibitor=data)


@exhibitor.route('/exhibitor/download/<dcp_id>')
@login_required
@exhibitor_required
def download(dcp_id):
    dcp = Dcp.query.get_or_404(dcp_id)
    app = current_app._get_current_object()
    return send_from_directory(app.config['TORRENT_FOLDER'],
                               dcp.name+".torrent",
                               as_attachment = True)

@exhibitor.route('/exhibitor/trailers')
@login_required
@exhibitor_required
def trailers():
    _exhibitor = current_user.exhibitor
    _trailers = Dcp.query.join(Movie).\
                         filter(Dcp.contentkind == Dcp.TRAILER,
                                 Dcp.valid == True).\
                         order_by(Movie.releasedate.desc()).all()
    return render_template('exhibitor/trailers.html',
                           exhibitor = _exhibitor,
                           trailers = _trailers,
                           DistributionStatus = DistributionStatus)

#@exhibitor.route('/exhibitor/movies')
#@login_required
#@exhibitor_required
def movies():
    _exhibitor = current_user.exhibitor
    _dcp_with_autorisation = Dcp.query.join(Movie).join(Distribution).\
                         filter(Dcp.contentkind == Dcp.FEATURE,
                                Distribution.exhibitor == _exhibitor).\
                         order_by(Movie.releasedate.desc()).all()
    _dcp_without_autorisation = Dcp.query.join(Movie).join(Distribution).\
                         filter(Dcp.contentkind == Dcp.FEATURE,
                                Distribution.exhibitor != _exhibitor).\
                         order_by(Movie.releasedate.desc()).all()

    items = _exhibitor.get_movies_list_with_statusv2()

    return render_template('exhibitor/list_movies.html',
                           exhibitor = _exhibitor,
                           items = items,
                           DistributionStatus = DistributionStatus)



@exhibitor.route('/exhibitor/shorts')
@login_required
@exhibitor_required
def shorts():
    _exhibitor = current_user.exhibitor
    _shorts = Short.query.all()
    return render_template('exhibitor/shorts.html',
                           exhibitor = _exhibitor,
                           shorts = _shorts)

def torrents_example():
    client = {}
    _torrents = []
    _torrent = {
        u'name'    : u'Charlie',
        u'hash'    : u'adlsjdlkzajdlkza',
        u'progress': 85.2,
        u'status'  : u'downloading'}
    _torrents.append(_torrent)
    _torrent = {
        u'name'    : u'iFati',
        u'hash'    : u'idekjazhdkj',
        u'progress': 100.0,
        u'status'  : u'seeding'}
    _torrents.append(_torrent)
    client['name']= 'localhost'
    client['torrents']= _torrents
    return client


@exhibitor.route('/exhibitor/downloads')
@login_required
@exhibitor_required
def downloads():
    app = current_app._get_current_object()
    exhibitor = current_user.exhibitor
    tclient = Client.query.filter_by(ipt = exhibitor.iptinc).first()
    if tclient is None:
        msg= u'Imposible de trouver un client torrent pour {}'.format(exhibitor)
        app.logger.error(msg)
        flash(msg)
        return redirect(url_for('.home'))
    return render_template('exhibitor/downloads.html',
            exhibitor = exhibitor,
            tclient = tclient)


distribution_fields = {
    'dcpid': fields.Integer,
    'dcp': fields.String,
    'exhibitor_cncid': fields.Integer,
    'exhibitorid': fields.Integer,
    'exhibitor': fields.String,
    'autorisation_date': fields.DateTime(dt_format='iso8601'),
    'started_transfer_date': fields.DateTime(dt_format='iso8601'),
    'finished_transfer_date': fields.DateTime(dt_format='iso8601'),
    'status': fields.String,
    'statusId': fields.Integer,
    'eta': fields.String(default='N/A'),
    'progress': fields.String(default='N/A')
}
dcps_fields = {
    'dcpid': fields.Integer,
    'name': fields.String,
    'size': fields.String,
    'contentkind': fields.String,
#    'exhibitors': fields.List(fields.Nested(distribution_fields)),
    }

movies_fields = {
    'movieid': fields.Integer,
    'title': fields.String,
    'original_title': fields.String,
    'releasedate': fields.DateTime(dt_format='iso8601'),
    'distributor':fields.String(attribute=u'distributor.name'),
    'dcps': fields.List(fields.Nested(dcps_fields))
}

@exhibitor.route('/exhibitor/moviedata')
def moviedata():
    app = current_app._get_current_object()
    exhibitor = Exhibitor.query.filter_by(name=u'TEST EXPLOITANT').one()
    movies = Movie.query.all()
    data_movies = {'data': [marshal(_d, movies_fields) for _d in movies]}

    _autorisations = Distribution.query.join(Dcp).filter(Distribution.exhibitor == exhibitor).all()
    data = {'autorisations': [marshal(_d, distribution_fields) for _d in _autorisations]}

    for _m in data_movies['data']:
        for _d in _m['dcps']:
            _d['autorisation'] = None
            for (idx,k) in enumerate(data['autorisations']):
                if k['dcpid'] == _d['dcpid']:
                    _d['autorisation'] = data['autorisations'][idx]
                break

    return jsonify(data_movies)


def datatable_example():
    client={}
    client['torrents'] = [
            {
                u'name' : u'Charlie',
                u'dcpname': u'DCP_CHALRIE',
                u'hash' : u'adlsjdlkzajdlkza',
                u'progress' :  u'85.2',
                u'status' : u'downloading'
                },
            {
                u'name' : u'Fati',
                u'dcpname': u'DCP_FATIMA_DASZEF',
                u'hash' : u'zoombala',
                u'progress' :  u'100',
                u'status' : u'seeding'
                }
            ]
    return client


def get_active_torrents(ipt):
    tclient = Client.query.filter_by(ipt = ipt).first()
    torrents = Torrent.query.filter(Torrent.client == tclient,
                                   Torrent.state != u'deleted').\
                            all()
    data = format_torrent_data(torrents)
    for (idx,_d) in enumerate(data):
        _d[u'DT_RowId'] = idx+1
    return data



@exhibitor.route('/exhibitor/gettorrents')
@login_required
@exhibitor_required
def gettorrents():
    exhibitor = current_user.exhibitor
    data = get_active_torrents(exhibitor.iptinc)
    return jsonify(data=data)


@exhibitor.route('/exhibitor/delete_dcp/<int:dcp_id>')
@login_required
@exhibitor_required
def delete_dcp(dcp_id):
    exhibitor = current_user.exhibitor
    dcp = Dcp.query.get_or_404(dcp_id)
    app = current_app._get_current_object()
    _msg=u"Suppression de {} en cours".format(dcp.name)
    flash(_msg)

    TorrentRequest.delete_torrent_by_hash(exhibitor.iptinc, dcp.torrent_hash)
    return  redirect(request.args.get("next") or url_for("exhibitor.downloads"))

@exhibitor.route('/exhibitor/verify_dcp/<int:dcp_id>')
@login_required
@exhibitor_required
def verify_dcp(dcp_id):
    exhibitor = current_user.exhibitor
    dcp = Dcp.query.get_or_404(dcp_id)
    app = current_app._get_current_object()
    _msg=u"Vérification de {} en cours".format(dcp.name)
    flash(_msg)

    TorrentRequest.verify_torrent_by_hash(exhibitor.iptinc, dcp.torrent_hash)
    return  redirect(request.args.get("next") or url_for("exhibitor.downloads"))


@exhibitor.route('/exhibitor/demands', methods=('GET', 'POST'))
@login_required
@exhibitor_required
def demands():
    exhibitor = current_user.exhibitor
    demands = MovieRequest.query.filter_by(exhibitor = exhibitor).all()
    return render_template('exhibitor/demands.html',
                            demands = demands)


@exhibitor.route('/exhibitor/distributiondata')
@login_required
@exhibitor_required
def distributiondata():
    """Return server side data."""
    print "exhibitor distribution data"
    # defining columns
    columns = []
    columns.append(ColumnDT('dcp.movie.title', 'movie'))
    columns.append(ColumnDT('dcp.name', 'dcp'))

app/templates/exhibitor/_table_distribution.html
{% from "_distribution_status.html" import contentkind_label %}

{% macro table_distribution_head() %}


<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap-datetimepicker.min.css') }}">
<link href="{{ url_for('static', filename='css/buttons.dataTables.css') }}" rel="stylesheet" type="text/css" />

{% endmacro %}

{% macro table_distribution() %}
        <table id="dt_110x" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Film </th>
                    <th>Nom</th>
                    <th>Distributeur</th>
                    <th>Exploitant</th>
                    <th>Autorisation</th>
                    <th>Début</th>
                    <th>Fin</th>
                    <th> </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Film </th>
                    <th>Nom</th>
                    <th>Distributeur</th>
                    <th>Exploitant</th>
                    <th>Autorisation</th>
                    <th>Début</th>
                    <th>Fin</th>
                    <th> </th>
                </tr>
            </tfoot>

            <tbody></tbody>
        </table>
{% endmacro %}

{% macro table_distribution_scripts(exhibitor=  none  , distributor= none, movie = none ) %}
<script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/datetime-moment.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datetimepicker.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/pdfmake.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/vfs_fonts.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/dataTables.buttons.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/buttons.flash.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/buttons.html5.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/buttons.print.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/myscript.js') }}"></script>

<script type="text/javascript" charset="utf-8">
// set jinja2 template variables as js vars
var params = {
    exhibitor: null,
    distributor: null,
    movie: null,
    dl_status_request: 'ALL'
};

{% if exhibitor is not none() %}
    params.exhibitor = {{exhibitor.exhibitorid}};
{% endif %}
{% if distributor is not none() %}
    params.distributor = {{distributor.distributorid}};
{% endif %}
{% if movie is not none() %}
    params.movie = {{movie.movieid}};
{% endif %}

{% if exhibitor.startauto %}
    params.dl_status_request = "DL_STARTED"
{% else %}
    params.dl_status_request = "DL_AUTHORIZED"
{% endif %}


$(document).ready(function(){

    update_locales();
    table_distribution('#dt_110x', "{{ url_for('.distributiondata') }}", params);


});

$('#myTab a').on('click', function (e) {
    e.preventDefault();
    var myTable = $('#dt_110x').DataTable();
    switch (this.id) {
        case "autorized-tab":
            params.dl_status_request = "DL_AUTHORIZED";
            myTable.order([[4, 'desc'] ]);
            break;
        case "started-tab":
            params.dl_status_request = "DL_STARTED";
            myTable.order([[5, 'desc'] ]);
            //myTable.language.emptyTable = 'Pas de téléchargement en cours';
            break;
         case "ended-tab":
            params.dl_status_request = "DL_FINISHED";
            myTable.order([[6, 'desc'] ]);
            break;
         case "all-tab":
         default:
            params.dl_status_request = "ALL"
            myTable.order([[4, 'desc'] ]);
            break;
    }
    myTable.ajax.reload();
    $(this).tab('show');
});
</script>
{% endmacro %}

app/templates/exhibitor/askformovie.html
<!-- extend base layout -->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}

<div class="page-header">
<h1>Demande de distribution de film</h1>
</div>

<div class="row">
    <div class="col-sm-6 col-md-6">
    <form class="form form-horizontal" method="post" role="form">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens="only") }}

        {{ wtf.form_field(form.name)    }}
        {{ wtf.form_field(form.to)      }}
        {{ wtf.form_field(form.movie)   }}
        {{ wtf.form_field(form.message) }}
        {{ wtf.form_field(form.submit)  }}

</form> 
    </div>
</div>

{% endblock %}

app/templates/exhibitor/demands.html
{% from "_common_macros.html" import RenderON %}
{% extends "base.html" %}

{% block page_content %}

<div class="modal fade" id="AskForMovieModal" role="dialog" tabindex="-1" aria-labelledby="myModalLabel"  >
    <div class="modal-dialog" role="document">
        <form id ='formAskForMovie' class="form form-horizontal" method="post" role="form" action='askformovie'>
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Demande de téléchargement de DCP</h4>
                </div>
                <div class="modal-body">
                    <div style="display:none;">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                    </div>

                    <div class="form-group  required"><label class="control-label" for="name">Exploitant</label>
                        <input class="form-control" id="name" name="name"
                        required type="text" value="TEST EXPLOITANT">
                    </div>

                    <div class="form-group  required"><label class="control-label" for="to">Envoyer à</label>
                        <input class="form-control" id="to" name="to"
                        required type="text" value="TEST DISTRIBUTEUR">
                    </div>

                    <div class="form-group  required"><label class="control-label" for="movie">Film</label>
                        <input class="form-control" id="movie" name="movie"
                        required type="text" value="MON FILM">
                    </div>

                    <div class="form-group  required"><label class="control-label" for="message">Message</label>
                        <textarea rows="15" class="form-control" id="message" name="message" required>
                            Bonjour TEST DISTRIBUTEUR,
                        </textarea>
                    </div>

                </div>
                <div class="modal-footer">
                    <input class="btn btn-primary" id="submit" name="submit" type="submit" value="Envoyer le message">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>

                </div>
            </div>
        </form>
    </div>
</div>


<div class="container-fluid">
    <div class = "row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-header" >
                    <h3> Historique des demandes de films </h3>
                </div>
                <div class="panel-body" >
                    <table id="DefaultTable" class="table table-striped table-bordered table-condensed table-summary">
                        <thead>
                            <tr> <th> Demandé le </th>
                                <th> Par </th>
                                <th> Film  </th>
                                <th> Autorisé ? </th>
                                <th> </th>
                            </tr>
                        </thead>
                        {% for item in demands %}
                        <tr>
                            <td> {{ item.demand_date}} </td>
                            <td>
                                <a href="{{ url_for('exhibitor_distributors.details',
                                id   = item.distributor.distributorid) }}" />
                                    {{ item.distributor.name }}
                                </a>
                            </td>

                            <td> <a href="{{ url_for('exhibitor_movies.details', id = item.movieid) }}" />
                                    {{item.movie.title}} </a>
                            </td>
                            <td> {{ RenderON(item.is_autorised, no='En attente') }}
                            </td>

                            <td>
        <button type="button" class="btn btn-primary"
            id="askForMovieBtn"
            data-toggle="modal"
            data-target="#AskForMovieModal"
            data-movieid="{{item.movieid}}" >
            Refaire une demande
        </button>

                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/datetime-moment.js') }}"></script>

<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
    update_locales();
    var table =$('#DefaultTable').DataTable({
        'columnDefs': [
        {
            'targets': 0,
            'visible': true,
            "render": function ( data, type, row ) {
                return render_date(data,type);
            }
        }
         ],

    "order" : [[0, 'desc']]
    });
} );

$('#AskForMovieModal').on('show.bs.modal', function(event) {

    var button = $(event.relatedTarget);
    var myurl = 'movies/askformovie/'+ button.data('movieid');
    $.getJSON(myurl, function(data){
        var $modalwindow = $('#AskForMovieModal');
        $modalwindow.find('#formAskForMovie').attr('action',myurl);
        $modalwindow.find('#formAskForMovie #name').attr('value',data.exhibitor);
        $modalwindow.find('#formAskForMovie #to').attr('value',data.distributor);
        $modalwindow.find('#formAskForMovie #movie').attr('value',data.movie);
        $modalwindow.find('#formAskForMovie #message').text(data.body);
    });
});

</script>

{% endblock %}

app/templates/exhibitor/edit_preferences.html
{% extends "baseV2.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block head %}
{{ super() }}
{% endblock %}


{% block page_content %}
<div class ="container-fluid">
    <div class="page-header">
        <h1> Préfrérences utilisateur </h1>
    </div>
</div>

<div class="container-fluid">
    <div class="row" >
        <div class="col-md-8">
            {{ wtf.quick_form(form, form_type='horizontal', horizontal_columns = ('sm',4,8)) }}
        </div>
    </div>
</div>



{% endblock %}

{% block scripts %}

{{ super() }}

{% endblock %}

app/templates/exhibitor/exhibitor_view.html
{% extends "baseV2.html" %}
{% from "exhibitor/_table_distribution.html" import table_distribution_head %}
{% from "exhibitor/_table_distribution.html" import table_distribution %}
{% from "exhibitor/_table_distribution.html" import table_distribution_scripts %}

{% block head %}
{{ super() }}
{{ table_distribution_head() }}
{% endblock %}

{% block page_content %}


<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-sm-6">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    État de la connexion
                </div>
                <div id="div_machinestatus" class="panel-body">
                    En cours de vérification
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-6">
            <a href="{{ url_for('exhibitor_movies.home') }}" class="btn btn-primary" role="button">
                Sorties nationales <br>  disponibles sur Indé-CP
            </a>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class = "row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-header" >
                    <h3> Distribution </h3>

                </div>

                <div class="panel-body" >
                <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
                    {% if exhibitor.startauto %}
                    <li role='presentation' class="active">
                        <a  id="started-tab"  href="#started" role="tab" aria-controls="started" aria-selected="false">
                            Téléchargements en cours </a>
                    </li>
                    {% else %}
                    <li role='presentation' class="active">
                        <a id="autorized-tab"  href="#autorized" role="tab" aria-controls="autorized" aria-selected="true">
                            Téléchargements autorisés</a>
                    </li>

                    <li role='presentation'>
                        <a  id="started-tab"  href="#started" role="tab" aria-controls="started" aria-selected="false">
                            Téléchargement en cours </a>
                    </li>
                    {%endif%}
                    <li role='presentation'>
                        <a id="ended-tab"  href="#ended" role="tab" aria-controls="ended" aria-selected="false">
                            Terminés récemment </a>
                    </li>
                    <li role='presentation'>
                        <a id="all-tab" href="#all" role="tab" aria-controls="all" aria-selected="false">
                           Tout les téléchargements
                        </a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    {% if exhibitor.startauto %}
                    <div class="tab-pane" id="started" role="tabpanel" aria-labelledby="started-tab">
                        <h5> Téléchargements démarrés </h5>
                    </div>


                    {% else %}
                    <div class="tab-pane active" id="autorized" role="tabpanel" aria-labelledby="autorized-tab">
                        <h5> Téléchargements autorisés </h5>
                    </div>
                    <div class="tab-pane" id="started" role="tabpanel" aria-labelledby="started-tab">
                        <h5> Téléchargements démarrés </h5>
                    </div>

                    {% endif %}
                    <div class="tab-pane" id="ended" role="tabpanel" aria-labelledby="ended-tab">
                        <h5> Téléchargements terminés </h5>
                    </div>
                    <div class="tab-pane" id="all" role="tabpanel" aria-labelledby="all-tab">
                        <h5> Tout les téléchargements </h5>
                    </div>

                    {{ table_distribution() }}

                </div>

            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
{{ super() }}

<script type="text/javascript" src="{{ url_for('static', filename='js/exhibitor.js') }}"></script>
<script>
function GetCinemaStatus() {
    var url = '{{ url_for('.getcinemastatus') }}';
    $.getJSON( url, {
    })
    .done(function( data ) {
        var div = $("#div_machinestatus");
        var exhibitor = data['exhibitor'];
        var panel = div.parent();
        if ( exhibitor['status'] == 'STARTED') {
            div.text('La machine de réception est active dans votre cinéma.');
            panel.removeClass("panel-warning");
            panel.addClass("panel-success");
        } else {
            div.text("ATTENTION: La machine de réception dans votre cinéma n'est pas active.");
            panel.removeClass("panel-warning");
            panel.addClass("panel-danger");
        }
    });
};

$( document ).ready(function() {
        GetCinemaStatus();
});

setInterval( function () {
        GetCinemaStatus();
}, 5000 )


</script>

{{ table_distribution_scripts(exhibitor=exhibitor) }}

{% endblock %}