app/distributor/forms.py
# -*- coding: utf-8 -*-
# -*- Mode: Python -*-
# vim:si:ai:et:sw=4:sts=4:ts=4

from flask_wtf import Form
from wtforms import SubmitField, SelectField, SelectMultipleField
from wtforms import widgets
from ..models import Dcp

class MultiCheckboxField(SelectMultipleField):
    widget = widgets.Input()
    option_widget = widgets.CheckboxInput()

class ConfirmationForm(Form):
    submit = SubmitField(u'Valider la distribution')
    cancel = SubmitField(u'Annuler')


choices = [
    (Dcp.TRAILER, u'Bande Annonce (TLR)'),
    (Dcp.FEATURE, u'Long métrage (FTR)'),
]

class SelectDistributionTypeForm(Form):
    dist_type = MultiCheckboxField('A distribuer ', choices=choices)
    submit = SubmitField('Continuer')
    cancel = SubmitField('Annuler')

app/exhibitor/forms.py
# -*- coding: utf-8 -*-
# -*- Mode: Python -*-

from flask_wtf import FlaskForm
from wtforms import widgets
from wtforms import TextField, TextAreaField, SubmitField
from wtforms import RadioField
from wtforms import SelectField
from wtforms import StringField
from wtforms import DateField
from wtforms.fields.html5 import EmailField
from wtforms import validators, ValidationError
class ContactForm(FlaskForm):
    name = TextField(u"Name",  [validators.Required()])
    email = TextField(u"Email",  [validators.Required()])
    subject = TextField(u"Sujet",  [validators.Required()])
    message = TextAreaField(u"Message",  [validators.Required()])
    submit = SubmitField(u"Send")

class AskforMovieForm(FlaskForm):
    name = TextField(u"Exploitant",  [validators.Required()])
    to = TextField(u"Envoyer à",  [validators.Required()])
    movie = TextField(u"Film",  [validators.Required()])
    programed_date = DateField(u"Date programmation", format=u"%d/%m/%Y", validators=(validators.Optional(),))
    message = TextAreaField(u"Message")
    submit = SubmitField(u"Envoyer le message")

class ReadonlyTextField(TextField):
      def __call__(self, *args, **kwargs):
          kwargs.setdefault('readonly', True)
          return super(ReadonlyTextField, self).__call__(*args, **kwargs)

class UserPropertiesForm(FlaskForm):
    name =      ReadonlyTextField(u"Cinéma")
    cncid =     TextField(u"Numéro d'autorisation CNC",  [validators.DataRequired()])
    contact =   TextField(u"Contact",  [validators.DataRequired()])
    email1 =     EmailField(u"Email principal",  [validators.DataRequired(),
                    validators.Email()])
    email2 =     EmailField(u"Email 2" )
    email3 =     EmailField(u"Email 3" )
    phone = StringField(u'Téléphones(s) -- séparé par des virgules')
    address =   TextField(u"Adresse",  [validators.DataRequired()])
    zipcode   = StringField(u'Code postal')
    dept =      TextField(u"Département",  [validators.DataRequired()])
    city =      TextField(u"Ville",  [validators.DataRequired()])
    nbscreens = TextField(u"Nombre d'écrans",  [validators.DataRequired()])

    startauto = SelectField(u'Démarrage automatique des transferts ?',
            validators = [ validators.Required() ],
            choices = [('yes',
                u"Oui -- Démarrer automatiquement le tansfert de DCP \
                        dés qu'il est autorisé par le distributeur"),
                ('no',
                    u'Non -- Pas de  démarrage automatique des transferts')],
                default = 'no')
    submit =    SubmitField(u"Envoyer")
    cancel =    SubmitField(u'Annuler les modifications')

app/distributor/__init__.py
from flask import Blueprint

distributor = Blueprint('distributor', __name__)

distributor_movies = Blueprint('distributor_movies', __name__, template_folder="distributor/movies/")
distributor_movie_requests = Blueprint('distributor_movie_requests', __name__, template_folder="distributor/movie_requests/")

from . import views
from . import forms
from . import distribution
from . import movies
from . import movie_requests

app/distributor/views.py
# -*- coding: utf-8 -*-
# -*- Mode: Python -*-

import os.path
import sys

from flask import render_template, session, redirect, url_for, request
from flask import current_app, flash, jsonify
from flask_login import login_required, current_user
from flask_wtf import Form
from sqlalchemy import func

from . import distributor
from .. import db
from ..models import User, Movie, Exhibitor, DistributionStatus, Dcp, Short
from ..models import Distribution, MovieRequest, Distributor
from ..email import send_email, build_to
from ..decorators import distributor_required
from .forms import ConfirmationForm, SelectDistributionTypeForm
from .distribution import do_distribution

from app.datatables import ColumnDT, DataTables
from app.exceptions import TucoException
from app.common   import redirect_url

from string import upper

@distributor.route('/distributor/')
@distributor.route('/distributor/home')
@login_required
@distributor_required
def home():
    _d = current_user.distributor
    if _d.is_agencecm:
        shorts = Short.query.filter_by(distributor = _d).all()
        return render_template('distributor/agencecm_view.html',
                           title='Tuco',
                           distributor = _d,
                           shorts = shorts
                    )
    else:
        movies =_d.movies.filter_by(valid=True).order_by(Movie.releasedate.desc()).limit(4)
        return render_template('distributor/distributor_view.html',
                           title='Tuco',
                           distributor = _d,
                           movies = movies
                           )

@distributor.route('/distributor/distribute_movie/<int:movieid>', methods=['GET','POST'])
@login_required
@distributor_required
def distribute_movie(movieid):
    app = current_app._get_current_object()
    movie = Movie.query.get_or_404(movieid)
    exhibitors = Exhibitor.all_valid_exhibitors()

    form = Form()
    if form.validate_on_submit():
        if request.form.get('cancel'):
            flash(u'Distribution annulée')
            return redirect(url_for('distributor_movies.details', id = movie.movieid ))

        elif request.form.get('submit'):
            session['exhibitors'] = request.form.getlist('exhibitors')
            session['selected_dcps'] =  request.form.getlist('dcps')
            return redirect(url_for('distributor.distribute_movie_confirmation',
                                movieid = movieid))

        else:
            _msg=u'unkown POST directive'
            app.logger.error(_msg)
            flash(_msg)


    return render_template('distributor/distribute_movie.html',
        movie = movie,
        form = form)



@distributor.route('/distributor/distribute_movie_confimation/<int:movieid>', methods=['GET','POST'])
@distributor.route('/distributor/distribute_movie_confimation/<int:movieid>/<int:exhibitorid>', methods=['GET','POST'])
@login_required
@distributor_required
def distribute_movie_confirmation(movieid, exhibitorid=None):
    movie = Movie.query.get_or_404(movieid)
    app = current_app._get_current_object()
    if exhibitorid is None:
        exhibitors   = [Exhibitor.query.get(_id) for _id in session['exhibitors']]
        selected_dcps = [Dcp.query.get(_id) for _id in session['selected_dcps']]
    else:
        exhibitors = [Exhibitor.query.get_or_404(exhibitorid)]
        selected_dcps = movie.get_all_dcps()
    if not exhibitors:
        _msg = u'Pas d\'exploitant sélectionné: Distribution impossible'
        flash(_msg)
        current_app.logger.warning(_msg)
        return redirect(url_for('.distribute_movie', movieid = movieid))

    form = ConfirmationForm()
    if form.validate_on_submit():
        if form.cancel.data:
            flash(u'Distribution annulée')
            return redirect(url_for('distributor_movies.details', id = movieid))
        elif form.submit.data:
            exhibitors_ok = []
            for exhibitor in exhibitors:
                try:
                     _added_dcps = do_distribution(movie, selected_dcps, exhibitor)
                except TucoException as err:
                    flash(err.message)
                    continue
                if _added_dcps is not None:
                    exhibitors_ok.append(exhibitor)
                else:
                    _msg = u"L'exploitant {} est déjà autorisé à recevoir :{}".\
                            format(exhibitor, ' '.join([ _dcp.name for _dcp in selected_dcps] ))
                    flash(_msg)
            # send recap email to ditributor
            if exhibitors_ok:
                try:
                    send_email(
                        build_to(current_user.distributor),
                        u'Récapitulatif distribution de {}'.format(movie.title),
                        'distributor/email/recap_distribution',
                        cc = [app.config['TUCO_ADMIN']],
                        movie = movie,
                        selected_dcps = selected_dcps,
                        exhibitors = exhibitors_ok)
                except:
                    _msg = u'Something goes wrong in expedition'
                    flash(_msg)
                    _msg= u'Unexpected error:', sys.exc_info()[0]
                    current_app.logger.error(_msg)
            return redirect(url_for('distributor_movies.details', id = movieid))
        else:
            current_app.logger.error(u'Something goes wrong')
            return redirect(url_for('distributor_movies.details', id = movieid))
    return render_template('distributor/distribute_movie_confirmation.html',
                            movie = movie,
                            dcps = selected_dcps,
                            exhibitors = exhibitors,
                            form = form)

@distributor.route('/distributor/exhibitors')
@login_required
@distributor_required
def exhibitors():
    exhibitors = Exhibitor.query.order_by(Exhibitor.name)
    return render_template('distributor/exhibitors.html',
                            exhibitors = exhibitors)

@distributor.route('/distributor/exhibitor/<int:exhibitorid>', methods=['GET','POST'])
@login_required
@distributor_required
def show_exhibitor(exhibitorid):
    _d = current_user.distributor
    exhibitor = Exhibitor.query.get_or_404(exhibitorid)

    return render_template('distributor/exhibitor.html',
                           exhibitor = exhibitor,
                           distributor= _d)

@distributor.route('/distributor/list_demands', methods=('GET', 'POST'))
@login_required
@distributor_required
def list_demands():
    distributor = current_user.distributor
    demands = MovieRequest.query.filter_by(distributor = distributor).all()
    return render_template('distributor/list_demands.html',
                            demands = demands)

@distributor.route('/distributor/distributiondata')
@login_required
@distributor_required
def distributiondata():
    """Return server side data."""
    # defining columns
    columns = []
    columns.append(ColumnDT('dcp.movie.title','movie'))
    columns.append(ColumnDT('dcp.name','dcp' ))
    columns.append(ColumnDT('dcp.movie.distributor.name','distributor'))
    columns.append(ColumnDT('exhibitor.name', 'exhibitor'))
    columns.append(ColumnDT('autorisation_date', 'autorisation_date', search_like = False, search_datetime_range = True))
    columns.append(ColumnDT('started_transfer_date','started_transfer_date',  search_like = False, search_datetime_range = True))
    columns.append(ColumnDT('finished_transfer_date', 'finished_transfer_date', search_like = False, search_datetime_range = True))
    columns.append(ColumnDT('dcp.contentkind', 'contentkind', searchable  =False))
    columns.append(ColumnDT('dcp.movie.movieid', 'movieid',  searchable  =False))
    columns.append(ColumnDT('dcp.movie.distributor.distributorid','distributorid', searchable  =False))
    columns.append(ColumnDT('exhibitor.exhibitorid', 'exhibitorid', searchable  =False))
    columns.append(ColumnDT('dcp.dcpid', 'dcpid', searchable  =False))
    columns.append(ColumnDT('dcp.valid', 'valid', searchable  =False))
    columns.append(ColumnDT('exhibitor.city', 'city', searchable  =False, filter= upper) )

    try:
        _e = int( request.values['exhibitor'])
    except ValueError:
        _e = None

    try:
        _d = int( request.values['distributor'])
    except ValueError:
        _d = None

    try:
        _m = int( request.values['movie'])
    except ValueError:
        _m = None

    query = db.session.query(Distribution).join(Dcp).join(Exhibitor).join(Movie).join(Distributor)
    if _e is not None:
        query = query.filter(Exhibitor.exhibitorid == _e)
    if _d is not None:
        query = query.filter(Distributor.distributorid == _d)
    if _m is not None:
        query = query.filter(Movie.movieid == _m)
    from sqlalchemy import or_, and_
    query = query.filter(or_(
        and_(Dcp.contentkind == Dcp.FEATURE, Distribution.isauthorised ==True),
        and_( Dcp.contentkind == Dcp.TRAILER,
            or_( Distribution.autorisation_date != None,  Distribution.started_transfer_date !=None)
            )
        ))

    # instantiating a DataTable for the query and table needed
    rowTable = DataTables(request.args, Distribution, query, columns)
    # returns what is needed by DataTable
    return jsonify(rowTable.output_result())


from flask_restful import fields, marshal
from flask.json import dumps

class StatusField(fields.Raw):
    DISTRIBUTION_STATUS = {
            DistributionStatus.DL_NOT_AUTHORIZED : u'Distribution not allowed',
            DistributionStatus.DL_AUTHORIZED : u'Distribution allowed',
            DistributionStatus.DL_STARTED : u'Distribution started',
            DistributionStatus.DL_FINISHED : u'Distribution finished',
            DistributionStatus.DL_ERROR : u'Distribution error',
            }


    def format(self, value):
        return self.DISTRIBUTION_STATUS[value]

app/exhibitor/__init__.py
from flask import Blueprint

exhibitor = Blueprint('exhibitor', __name__)
exhibitor_movies = Blueprint('exhibitor_movies', __name__, template_folder="exhibitor/movies/")
exhibitor_movie_requests = Blueprint('exhibitor_movie_requests', __name__, template_folder="exhibitor/movie_requests/")
exhibitor_distributors = Blueprint('exhibitor_distributors', __name__, template_folder="exhibitor/distributors/")
exhibitor_tags = Blueprint('exhibitor_tags', __name__, template_folder="exhibitor/tags/")
exhibitor_shorts = Blueprint('exhibitor_shorts', __name__, template_folder="exhibitor/shorts/")


from . import views
from . import movies
from . import movie_requests
from . import distributors
from . import forms
from . import actions
from . import tags
from . import shorts

app/templates/distributor/_table_distribution.html
{% from "_distribution_status.html" import contentkind_label %}

{% macro table_distribution_head() %}


<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap-datetimepicker.min.css') }}">
<link href="{{ url_for('static', filename='css/buttons.dataTables.css') }}" rel="stylesheet" type="text/css" />

{% endmacro %}

{% macro table_distribution() %}
<div class="row">
    <div class="col-lg-12">

        <table id="dt_110x" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Film </th>
                    <th>Nom DCP </th>
                    <th>Distrib</th>
                    <th>Exploitant</th>
                    <th>Autorisation</th>
                    <th>Début</th>
                    <th>Fin</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Film </th>
                    <th>Nom DCP</th>
                    <th>Distrib</th>
                    <th>Exploitant</th>
                    <th>Autorisation</th>
                    <th>Début</th>
                    <th>Fin</th>
                </tr>
            </tfoot>

            <tbody></tbody>
        </table>
    </div>
</div>
{% endmacro %}

{% macro table_distribution_scripts(exhibitor=  none  , distributor= none, movie = none ) %}
<script type="text/javascript" src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/datetime-moment.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datetimepicker.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/pdfmake.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/vfs_fonts.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/dataTables.buttons.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/buttons.flash.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/buttons.html5.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/buttons.print.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/myscript.js') }}"></script>

<script type="text/javascript" charset="utf-8">
$(document).ready(function(){

    // set jinja2 template variables as js vars
    var exhibitor = null;
    var distributor = null;
    var movie = null;
    {% if exhibitor is not none() %}
    exhibitor = {{exhibitor.exhibitorid}};
    {% endif %}
    {% if distributor is not none() %}
    distributor = {{distributor.distributorid}};
    {% endif %}
    {% if movie is not none() %}
    movie = {{movie.movieid}};
    {% endif %}


    update_locales();

    var myTable = $('#dt_110x').DataTable({
        "processing": true,
        "serverSide": true,
        "pageLength": 50,
        "lengthMenu": [ [ 25, 50, 100, -1], [ 25, 50, 100, "Tous"] ],
        "ajax": {
            "url": "{{ url_for('distributor.distributiondata') }}",
            "data": function ( d) {
                d.exhibitor = exhibitor
                d.distributor = distributor
                d.movie = movie
            }
        },
        dom: 'Blfrtip',
        buttons: [
            'csv', 'pdf', 'print'
        ],
        "columns": [
            // 0 -- film name
        {
            "data": "movie",
            "name": "movie",
            "render": function ( data, type, row ) {
                var todisplay = '<a href="/distributor/movies/details/' + row.movieid + '" />' +
                    data +
                '</a>' ;
                return todisplay;
            }
        },
        // 1 -- dcp name
        {
            "data": "dcp",
            "name": "dcp",
            "render": function ( data, type, row ) {
                var contentkind = render_contentkind_label(row.contentkind, false);
                var $todisplay = $("<div>");
                var cel_text = $('<span>', {
                    'class' : 'small',
                    'text': data});
                if (row.valid == 'False') {
                    cel_text.addClass('text-muted');
                    cel_text.text('');
                    $('<s>',{
                        'text': data}).appendTo(cel_text);
                    contentkind = render_contentkind_label(row.contentkind, true);
                } else {
                    contentkind = render_contentkind_label(row.contentkind,false);
                }
                $todisplay.append(contentkind);
                cel_text.appendTo($todisplay);
                return $todisplay.html();
             }
        },
         // 2 -- Distributor
        {
            "data": "distributor",
            "name": "distributor",
            "render": function ( data, type, row ) {
                return data;
            }
        },
         // 3 -- Exhibitor
        {

            "data": "exhibitor",
            "name": "exhibitor",
            "render": function ( data, type, row ) {
		var $todisplay = $("<div>");
                link = $('<a>', {
                    'href': '/distributor/exhibitor/' + row.exhibitorid ,
                    'text':  row.city + ' - ' +data
                });

                link.appendTo($todisplay);
                return $todisplay.html();

            }
        },
         // 4 -- Autorisation Date
        {

            "data": "autorisation_date",
            "render": function ( data, type, row ) {
                return render_datetime(data,type);
            }
        },
         // 5 -- Start Date
        {
            "data": "started_transfer_date",
            "render": function ( data, type, row ) {
                return render_datetime(data,type);
            }
        },
         // 6 -- End Date
        {
            "data": "finished_transfer_date",
            "render": function ( data, type, row ) {
                return render_datetime(data,type);
            }
        },
            ],
        "order" : [[4, 'desc']]

    });

    // hide movie column when a movie is selected
    if (movie) {
       myTable.column('movie:name').visible(false);
    }
    // hide distributor column when a distributor is selected
    if (distributor) {
       myTable.column('distributor:name').visible(false);
    }
    // hide exhibitor column when a exhibitor is selected
    if (exhibitor) {
       myTable.column('exhibitor:name').visible(false);
    }


});
</script>
{% endmacro %}


{% macro table_distribution_exhibitor(messages) %}
<div class = "row">
<div class="table-responsive">
<table class="table table-striped table-bordered table-condensed" >
        <thead>
            <tr>
                <th> Film    </th>
                <th> Dcp </th>
                <th> Distributeur    </th>
                <th> Autorisation </th>
                <th> Début transfert </th>
                <th> Fin transfert </th>
            </tr>
        </thead>
        {% for _message in messages.items %}
            <tr>
                <td>
                {% if _message.dcp.name %}
                    {{ _message.dcp.movie.title }}
                {% else %}
                    Unknown DCP
                {% endif %}
            </td>
            <td> {{ contentkind_label(_message.dcp.contentkind)}} <small> {{_message.dcp.name}} </small> </td>
                <td>
                {% if _message.dcp.name %}
                    {{ _message.dcp.movie.distributor.name }}
                </a>
                {% else %}
                    Unknown DCP
                {% endif %}
                </td>
                <td> {{ _message.autorisation_date | mydatetime}} </td>
                <td> {{ _message.started_transfer_date | mydatetime}} </td>
                <td> {{ _message.finished_transfer_date | mydatetime}} </td>

            </tr>
        {% endfor %}
    </table>
</div>

{% if messages.has_prev %}
    <a href="{{ url_for('admin.distribution_status', page=messages.prev_num) }}">&lt;&lt; Newer messages</a> |
{% endif %}
{% if messages.has_next %}
    <a href="{{ url_for('admin.distribution_status', page=messages.next_num) }}">Older messages &gt;&gt;</a>
</div>
{% endif %}
{% endmacro %}

app/templates/distributor/agencecm_view.html
{% extends "base.html" %}
{% block page_content %}

<div class="page-header">
<h1> {{distributor.name}} </h1>
</div>

{% if shorts %}
<div class = "row" >
    {# <table id="short" class="display" > #}
        <table id="short" class="table table-striped table-bordered table-condensed" >
            <thead>
                <tr>
                    <th class="dt-justify" > Titre </th>
                    <th class="dt-center"> Réalisateur </th>
                    <th> Type </th>
                    <th> Dcp </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th> Titre </th>
                    <th> Réalisateur </th>
                    <th> Type </th>
                    <th> </th>
                </tr>
            </tfoot>

            {% for _item in shorts %}
            <tr>
                <td style="word-break:normal" > {{ _item.title }}            </td>

                <td class="dt-center"> {{ _item.director }} </td>
                <td> {{ _item.tags }} </td>

                <td>
                    {% if _item.dcps %}
                    <table id="dcp"  width="100%" class="table-striped  table-condensed">
                        {% for _dcp in _item.dcps %}
                        <tr>
                            <td  > <small> <p class="dcpname"> {{_dcp.name}} </p>  </small> </td>

                        </tr>
                        {% endfor %}
                    </table>
                    {% endif %}

                </td>

            </tr>
            {% endfor %}
        </table>
</div>
{% endif %}

<div class="row">
  <div class="col-sm-6 col-md-4">
    <table class="table table-striped table-bordered table-condensed" >
        <tr>
            <td> Distirbuteur </td>
            <td> {{distributor.name}} </td>
        </tr>
        <tr>
            <td> email </td>
            <td> {{distributor.user.email}} </td>
        </tr>

        {% if distributor.contact %}
        <tr>
            <td> Contact </td>
            <td> {{distributor.contact}} </td>
        </tr>
        {% endif %}

        {% if distributor.phone %}
        <tr>
            <td> Téléphone </td>
            <td> {{distributor.phone}} </td>
        </tr>
        {% endif %}

        {% if distributor.cnc_code %}
        <tr>
            <td> Code CNC </td>
            <td> {{distributor.cnc_code}} </td>
        </tr>
        {% endif %}



    </table>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
$(document).ready(function() {
    $('#short').DataTable( {
        'pageLength':50,
        "columns": [
        { "width": "30%" },
        { "width": "20%" },
        { "width": "10%" },
            null
              ],
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                if  (column.index() != 3) {
                var select = $('<select><option class="form-control" value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                                );

                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );
                }
                column.data().unique().sort().each( function ( d, j ) {

                if  (column.index() != 3) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                }
                } );
            } );
        }
    } );
} );

</script>
{% endblock %}

app/templates/distributor/distributor_view.html
{% extends "base.html" %}

{% from "distributor/_table_distribution.html" import table_distribution_head %}
{% from "distributor/_table_distribution.html" import table_distribution %}
{% from "distributor/_table_distribution.html" import table_distribution_scripts %}
{% from "_distribution_status.html" import contentkind_label %}
{% from "_common_macros.html" import RenderEmails %}

{% block head %}
{{ super() }}
{{ table_distribution_head() }}
{% endblock %}


{% block page_content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container-fluid">
        <div class="col-md-6">
            <h2>  {{distributor.name}} </h2>
            <p><a class="btn btn-primary btn-lg" href="{{ url_for('distributor_movies.home') }}" role="button"> Mon catalogue</a></p>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-body" >
                    <table class="table table-condensed" >
                       {% if distributor.contact %}
                        <tr>
                            <td> Contact </td>
                            <td> {{distributor.contact}} </td>
                        </tr>
                        {% endif %}

                        {% if distributor.phone %}
                        <tr>
                            <td> Téléphone </td>
                            <td> {{distributor.phone}} </td>
                        </tr>
                        {% endif %}
                        {% if distributor.cnc_code %}
                        <tr>
                            <td> Code CNC </td>
                            <td> {{distributor.cnc_code}} </td>
                        </tr>
                        {% endif %}
                        <tr>
                            <td> emails </td>
                            <td>{{ RenderEmails(distributor.user) }}</td>
                        </tr>
                    </table>
                </div>
                <div class="panel-footer"> Si vous souhaitez modifier les informations ci-dessus, merci d'envoyer votre
                    demande à contacter@indecp.org
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <!-- Example row of columns -->

    <div class="row">
        <div class="col-md-4">
            <h3> Mes films récents: </h3>
        </div>
    </div>
    <div class="row">
        {% if movies %}
        {% for movie in movies %}
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body" >
                    <h4><a href="{{ url_for('distributor_movies.details', id= movie.movieid) }}"> {{ movie.title }} </a>  </h4>
                    <p>sortie nationale: {{movie.releasedate| datefr}}</p>

                    <div>
                            NB FTR :
                                {% if movie.nb_valid_ftr > 0 %}
                                <span class="glyphicon glyphicon-ok" style="color:green" aria-hidden="true"></span>
                                {% else %}
                                <span class="glyphicon glyphicon-remove" style="color:red" aria-hidden="true"></span>
                                {% endif %}
                                {{ movie.nb_valid_ftr}}
                    </div>
                    <div>
                            NB TLR :
                                {% if movie.nb_valid_tlr > 0 %}
                                <span class="glyphicon glyphicon-ok" style="color:green" aria-hidden="true"></span>
                                {% else %}
                                <span class="glyphicon glyphicon-remove" style="color:red" aria-hidden="true"></span>
                                {% endif %}
                                {{ movie.nb_valid_tlr}}
                    </div>
 
                    <p>
                    <a href="{{ url_for('.distribute_movie', movieid= movie.movieid) }}" class="btn btn-primary" role="button">Distribuer <br/> {{ movie.title}} </a>
                    </p>
                </div>
            </div>
        </div>

        {% endfor %}
        {%  endif  %}

    </div>

</div>

<div class="container-fluid">
    <div class = "row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-header" >
                    <h3> Distribution</h3>
                </div>
                <div class="panel-body" >
                    {{ table_distribution() }}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}

{{ table_distribution_scripts(distributor=distributor) }}

{% endblock %}